blueprint:
  name: Squirrel Scarer (Dual Cameras + Dual Sirens)
  description: >
    When motion is detected by either camera during a defined time window,
    this automation will activate both sirens and spray water via a Rachio switch.
  domain: automation
  input:
    motion_sensors:
      name: Motion Sensors
      description: Choose the two motion sensors (from Ring MQTT, should be binary_sensors)
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    sirens:
      name: Sirens
      description: Select the two sirens to activate
      selector:
        entity:
          domain: siren
          multiple: true
    sprinkler_switch:
      name: Rachio Water Switch
      description: Select the switch used to spray water (e.g., Rachio zone)
      selector:
        entity:
          domain: switch
    active_after:
      name: Active After
      description: Only trigger this automation after this time (e.g., 7:00 PM)
      default: "18:00:00"
      selector:
        time: {}
    active_before:
      name: Active Before
      description: Only trigger this automation before this time (e.g., 6:00 AM)
      default: "06:00:00"
      selector:
        time: {}

trigger:
  - platform: state
    entity_id: !input motion_sensors
    from: "off"
    to: "on"

condition:
  - condition: time
    after: !input active_after
    before: !input active_before

action:
  - repeat:
      for_each: !input sirens
      sequence:
        - service: siren.turn_on
          data:
            entity_id: "{{ repeat.item }}"
        - delay: "00:00:05"
        - service: siren.turn_off
          data:
            entity_id: "{{ repeat.item }}"
  - service: switch.turn_on
    data:
      entity_id: !input sprinkler_switch
  - delay: "00:00:02"
  - service: switch.turn_off
    data:
      entity_id: !input sprinkler_switch

mode: single
